import { createHash, randomUUID } from "node:crypto";
import {
  mkdirSync,
  readFileSync,
  readdirSync,
  renameSync,
  rmSync,
  unlinkSync,
  writeFileSync,
} from "node:fs";
import { join } from "node:path";
import {
  GRAFT_DESKTOP_MAX_BULK_TRANSFER_BYTES,
  GraftDesktopBulkTransferTicketSchema,
  GraftDesktopBulkUploadRequestSchema,
  type GraftDesktopBulkTransferTicket,
  type GraftDesktopBulkUploadRequest,
} from "@graft/shared";

const DEFAULT_TRANSFER_TTL_MS = 10 * 60 * 1_000;
export const MAX_BULK_TRANSFER_BYTES = GRAFT_DESKTOP_MAX_BULK_TRANSFER_BYTES;

interface TransferRecord {
  sessionId: string;
  ticket: GraftDesktopBulkTransferTicket;
  path: string;
  ready: boolean;
}

export interface BulkTransferStoreOptions {
  now?: () => number;
  randomId?: () => string;
  ttlMs?: number;
}

export interface ClaimedBulkUpload {
  path: string;
  release(): void;
}

function safeUploadFileName(value: string): string {
  const normalized = value.normalize("NFC");
  return normalized.length > 0 &&
    normalized.length <= 255 &&
    !normalized.includes("\0") &&
    !normalized.includes("/") &&
    !normalized.includes("\\") &&
    normalized !== "." &&
    normalized !== ".."
    ? normalized
    : "attachment";
}

function sha256(data: Buffer): string {
  return createHash("sha256").update(data).digest("hex");
}

/**
 * Ephemeral, session-scoped transfer staging. File paths are generated by the
 * host and never accepted from the client, so tunneled uploads cannot escape
 * the dedicated transfer directory.
 */
export class BulkTransferStore {
  private readonly records = new Map<string, TransferRecord>();
  private readonly claimedPaths = new Set<string>();
  private readonly now: () => number;
  private readonly randomId: () => string;
  private readonly ttlMs: number;

  constructor(
    private readonly root: string,
    options: BulkTransferStoreOptions = {},
  ) {
    mkdirSync(root, { recursive: true, mode: 0o700 });
    for (const entry of readdirSync(root)) {
      rmSync(join(root, entry), { recursive: true, force: true });
    }
    this.now = options.now ?? Date.now;
    this.randomId = options.randomId ?? randomUUID;
    this.ttlMs = options.ttlMs ?? DEFAULT_TRANSFER_TTL_MS;
  }

  createUpload(
    sessionId: string,
    rawRequest: unknown,
  ): GraftDesktopBulkTransferTicket {
    this.pruneExpired();
    const request: GraftDesktopBulkUploadRequest =
      GraftDesktopBulkUploadRequestSchema.parse(rawRequest);
    const transferId = this.randomId();
    const ticket = GraftDesktopBulkTransferTicketSchema.parse({
      transferId,
      direction: "upload",
      mediaType: request.mediaType,
      sizeBytes: request.sizeBytes,
      sha256: request.sha256,
      expiresAt: this.now() + this.ttlMs,
    });
    this.records.set(transferId, {
      sessionId,
      ticket,
      path: join(this.root, transferId),
      ready: false,
    });
    return ticket;
  }

  storeUpload(
    sessionId: string,
    transferId: string,
    data: Buffer,
  ): GraftDesktopBulkTransferTicket | null {
    this.pruneExpired();
    const record = this.records.get(transferId);
    if (
      !record ||
      record.sessionId !== sessionId ||
      record.ticket.direction !== "upload" ||
      record.ready ||
      data.length !== record.ticket.sizeBytes ||
      sha256(data) !== record.ticket.sha256
    ) {
      return null;
    }
    writeFileSync(record.path, data, { mode: 0o600, flag: "wx" });
    record.ready = true;
    return record.ticket;
  }

  createDownload(
    sessionId: string,
    data: Buffer,
    mediaType: string,
  ): GraftDesktopBulkTransferTicket {
    this.pruneExpired();
    if (data.length > MAX_BULK_TRANSFER_BYTES) {
      throw new Error("Bulk transfer exceeds the host limit");
    }
    const transferId = this.randomId();
    const ticket = GraftDesktopBulkTransferTicketSchema.parse({
      transferId,
      direction: "download",
      mediaType,
      sizeBytes: data.length,
      sha256: sha256(data),
      expiresAt: this.now() + this.ttlMs,
    });
    const path = join(this.root, transferId);
    writeFileSync(path, data, { mode: 0o600, flag: "wx" });
    this.records.set(transferId, {
      sessionId,
      ticket,
      path,
      ready: true,
    });
    return ticket;
  }

  readDownload(
    sessionId: string,
    transferId: string,
  ): { ticket: GraftDesktopBulkTransferTicket; data: Buffer } | null {
    this.pruneExpired();
    const record = this.records.get(transferId);
    if (
      !record ||
      record.sessionId !== sessionId ||
      record.ticket.direction !== "download" ||
      !record.ready
    ) {
      return null;
    }
    return { ticket: record.ticket, data: readFileSync(record.path) };
  }

  uploadedPath(sessionId: string, transferId: string): string | null {
    this.pruneExpired();
    const record = this.records.get(transferId);
    if (
      !record ||
      record.sessionId !== sessionId ||
      record.ticket.direction !== "upload" ||
      !record.ready
    ) {
      return null;
    }
    return record.path;
  }

  claimUpload(
    sessionId: string,
    transferId: string,
    fileName: string,
  ): ClaimedBulkUpload | null {
    this.pruneExpired();
    const record = this.records.get(transferId);
    if (
      !record ||
      record.sessionId !== sessionId ||
      record.ticket.direction !== "upload" ||
      !record.ready
    ) {
      return null;
    }
    const claimedDirectory = join(this.root, `claimed-${transferId}`);
    mkdirSync(claimedDirectory, { mode: 0o700 });
    const claimedPath = join(claimedDirectory, safeUploadFileName(fileName));
    renameSync(record.path, claimedPath);
    this.records.delete(transferId);
    this.claimedPaths.add(claimedDirectory);
    let released = false;
    return {
      path: claimedPath,
      release: () => {
        if (released) return;
        released = true;
        this.claimedPaths.delete(claimedDirectory);
        try {
          rmSync(claimedDirectory, { recursive: true, force: true });
        } catch {
          // The bounded temporary file may already have been removed.
        }
      },
    };
  }

  close(): void {
    for (const record of this.records.values()) {
      try {
        unlinkSync(record.path);
      } catch {
        // A reserved transfer may not have received bytes yet.
      }
    }
    for (const path of this.claimedPaths) {
      try {
        rmSync(path, { recursive: true, force: true });
      } catch {
        // Claimed files may have been released by their run owner.
      }
    }
    this.claimedPaths.clear();
    this.records.clear();
  }

  private pruneExpired(): void {
    const now = this.now();
    for (const [transferId, record] of this.records) {
      if (record.ticket.expiresAt > now) continue;
      try {
        unlinkSync(record.path);
      } catch {
        // Nothing was staged for this ticket.
      }
      this.records.delete(transferId);
    }
  }
}
